---
title: "Stuff they need to know"
output: html_document
---

## Prologue
- *Installation guide!* Start from scratch - maybe record a video?
- R
- rlang (what is that for again?!)
- Get GitHub account!
- Install git
- Include dummy repo where they can push/pull to see whether it worked.

### Packages needed
- **To be extended while material is growing.**
- `tidyverse` (explain that it's a bunch of packages)
- `rmarkdown`
- `effsize`

## Intro
- What is R, why R - **BE BRIEF**
- Encouraging stuff.
- Some words about packages and keeping your R up to date (take care of your R - it's like a houseplant.) **TO DO: FIND BETTER METAPHOR**
- Some words about tons of different styles/solutions/approaches + not to be discouraged by them.
- Manage expectations: We have 2 days. You won't be a pro, but you're gonna be fine and it will get better **if you continue using R!!!**
  - Nice: Show learning curve of programming. (Maybe also the time you save if you automate a task.)
  
### Get help
- Google (i.e. Stack Overflow) is your friend. Not knowing stuff by heart is fine.
- R documentation - **examples!**
- The `#rstats` hashtag on Twitter!
- Get a coding buddy.

## General things
- **PACKAGE. ORIENTED. WORKFLOW!**
- All code is beautiful, all approaches are valid, but if someone uses `setwd()` that is just **WRONG**.
- Still don't know whether I will use scripts or Rmarkdown. Probably Rmarkdown stuff, because that way, they will get used to it. But a script is quick and good for longer bits of code? Definitely show both and/or maybe call a script in the Rmd. Or let them do the exercises in scripts. (We want an html_document, not a notebook, right? I want no "dead code chunks" in there.)
- Present both `tidyverse` and base R. They will probably need to know about the `tidyverse`, but having a good base R knowledge is important.
- Throughout: Use GitHub. Let them have their own repo where they push code after every unit. Insert frequent push reminders into the seminar! Sensible commit messages.
  
## R Basics
- **AVOID "R is a calculator" examples at all costs**
- Variable names that work out for future you.

### Data structures
- Vectors, data frames etc.
- Do they need lists? **DO THEY NEED LISTS?!**

### Functions
- Input, argument, output
- Maaaayyybee write your own function? Can't hurt, can it?

## Data wrangling (yeehaaw)
- Read in data (simple for now).

- Filtering data
- Calculating new columns.
- Grouping.
- Summarising.

## Loops and similar concepts
- For and while.
- `apply()`? Should I go there?

## Real world struggles
- Read in data - advanced.
  - E.g. a bunch of text files (one per participant) in a folder.

## Stats
- t-Test
- Power?

- Report stats in their html file.

## Ideas
- Student course repo just with excercises? Solutions password protected? Possible?
